apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
#  annotations:
#    storageclass.kubernetes.io/is-default-class: "true"
provisioner: nfs-client-provisioner # or choose another name, must match deployment's env PROVISIONER_NAME'
parameters:
  archiveOnDelete: "true"
