apiVersion: v1
kind: Service
metadata:
  namespace: elasticsearch
  name: kibana
  labels:
    app: kibana
spec:
  selector:
    app: kibana
  ports:
    - port: 5601
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: elasticsearch
  name: kibana
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:7.0.0
          ports:
            - containerPort: 5601
          env:
            - name: SERVER_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SERVER_HOST
              value: "0.0.0.0"
            - name: ELASTICSEARCH_HOSTS
              value: http://elasticsearch.elasticsearch.svc.cluster.local:9200
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: kibana
  namespace: elasticsearch
spec:
  rules:
    - host: kibana.machloop.com
      http:
        paths:
          - path: "/"
            backend:
              serviceName: kibana
              servicePort: 5601