apiVersion: v1
kind: Service
metadata:
  name: cassandra
spec:
  type: NodePort
  ports:
  - name: cql
    port: 9042
    targetPort: 9042
    nodePort: 30042
  - name: thrift
    port: 9160
    targetPort: 9160
    nodePort: 30160
  selector:
    app: cassandra
